import { CanonicalSong } from "@akhustico/shared";

export const DEMO_SONGS: CanonicalSong[] = [
  {
    schemaVersion: "1.0",
    id: "demo-song-1",
    slug: "camino-acustico",
    title: "Camino Acústico",
    artist: "Andrés Acústico",
    album: "Sesiones de Medianoche",
    language: "es",
    originalAudioUrl: "https://assets.mixkit.co/music/preview/mixkit-guitar-acoustic-happy-energy-1111.mp3",
    audioHash: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    music: {
      originalKey: "G",
      preferredKey: "G",
      chordShapeKey: "G",
      capo: 0,
      tuning: "E A D G B E",
      bpm: 96,
      timeSignature: "4/4",
    },
    display: {
      fontScale: 1.0,
      readingMode: "large",
      showChords: true,
      showSections: true,
      autoscrollSpeed: 2,
    },
    tags: ["acústico", "guitarra", "balada", "favorito"],
    isFavorite: true,
    status: "ready",
    lastPracticedAt: new Date().toISOString(),
    lyrics: {
      sections: [
        {
          type: "intro",
          label: "Intro",
          lines: [
            {
              text: "[Instrumental de guitarra]",
              chords: [
                { symbol: "G", charIndex: 0 },
                { symbol: "Em", charIndex: 12 },
                { symbol: "C", charIndex: 20 },
                { symbol: "D", charIndex: 26 },
              ],
              startMs: 0,
              endMs: 8000,
            },
          ],
        },
        {
          type: "verse",
          label: "Verso 1",
          lines: [
            {
              text: "Despierta la mañana con un rayo de sol",
              chords: [
                { symbol: "G", charIndex: 0 },
                { symbol: "Em", charIndex: 22 },
              ],
              words: [
                { text: "Despierta", startMs: 8100, endMs: 8700 },
                { text: "la", startMs: 8750, endMs: 8900 },
                { text: "mañana", startMs: 8950, endMs: 9600 },
                { text: "con", startMs: 9650, endMs: 9800 },
                { text: "un", startMs: 9850, endMs: 10000 },
                { text: "rayo", startMs: 10050, endMs: 10500 },
                { text: "de", startMs: 10550, endMs: 10700 },
                { text: "sol", startMs: 10750, endMs: 11400 },
              ],
              startMs: 8100,
              endMs: 11500,
            },
            {
              text: "la guitarra me espera para darle calor",
              chords: [
                { symbol: "C", charIndex: 0 },
                { symbol: "D", charIndex: 22 },
              ],
              words: [
                { text: "la", startMs: 11600, endMs: 11750 },
                { text: "guitarra", startMs: 11800, endMs: 12400 },
                { text: "me", startMs: 12450, endMs: 12600 },
                { text: "espera", startMs: 12650, endMs: 13200 },
                { text: "para", startMs: 13250, endMs: 13600 },
                { text: "darle", startMs: 13650, endMs: 14100 },
                { text: "calor", startMs: 14150, endMs: 14900 },
              ],
              startMs: 11600,
              endMs: 15000,
            },
          ],
        },
        {
          type: "chorus",
          label: "Coro",
          lines: [
            {
              text: "Y canto al viento sin mirar atrás",
              chords: [
                { symbol: "C", charIndex: 0 },
                { symbol: "D", charIndex: 12 },
                { symbol: "G", charIndex: 24 },
              ],
              words: [
                { text: "Y", startMs: 15100, endMs: 15300 },
                { text: "canto", startMs: 15350, endMs: 15900 },
                { text: "al", startMs: 15950, endMs: 16100 },
                { text: "viento", startMs: 16150, endMs: 16800 },
                { text: "sin", startMs: 16850, endMs: 17100 },
                { text: "mirar", startMs: 17150, endMs: 17800 },
                { text: "atrás", startMs: 17850, endMs: 18600 },
              ],
              startMs: 15100,
              endMs: 18700,
            },
            {
              text: "cada nota me guía hacia mi libertad",
              chords: [
                { symbol: "Em", charIndex: 0 },
                { symbol: "C", charIndex: 15 },
                { symbol: "D", charIndex: 26 },
                { symbol: "G", charIndex: 34 },
              ],
              words: [
                { text: "cada", startMs: 18800, endMs: 19100 },
                { text: "nota", startMs: 19150, endMs: 19600 },
                { text: "me", startMs: 19650, endMs: 19800 },
                { text: "guía", startMs: 19850, endMs: 20400 },
                { text: "hacia", startMs: 20450, endMs: 20800 },
                { text: "mi", startMs: 20850, endMs: 21000 },
                { text: "libertad", startMs: 21050, endMs: 22200 },
              ],
              startMs: 18800,
              endMs: 22500,
            },
          ],
        },
      ],
    },
    melody: [
      { timeMs: 8100, frequency: 196.0, midi: 55.0, note: "G3", confidence: 0.95, voiced: true },
      { timeMs: 8500, frequency: 220.0, midi: 57.0, note: "A3", confidence: 0.94, voiced: true },
      { timeMs: 8950, frequency: 246.9, midi: 59.0, note: "B3", confidence: 0.96, voiced: true },
      { timeMs: 10050, frequency: 261.6, midi: 60.0, note: "C4", confidence: 0.93, voiced: true },
      { timeMs: 10750, frequency: 293.7, midi: 62.0, note: "D4", confidence: 0.97, voiced: true },
      { timeMs: 11800, frequency: 329.6, midi: 64.0, note: "E4", confidence: 0.92, voiced: true },
      { timeMs: 12650, frequency: 293.7, midi: 62.0, note: "D4", confidence: 0.95, voiced: true },
      { timeMs: 14150, frequency: 246.9, midi: 59.0, note: "B3", confidence: 0.94, voiced: true },
      { timeMs: 15350, frequency: 329.6, midi: 64.0, note: "E4", confidence: 0.96, voiced: true },
      { timeMs: 16150, frequency: 369.99, midi: 66.0, note: "F#4", confidence: 0.95, voiced: true },
      { timeMs: 17150, frequency: 392.0, midi: 67.0, note: "G4", confidence: 0.98, voiced: true },
      { timeMs: 17850, frequency: 329.6, midi: 64.0, note: "E4", confidence: 0.94, voiced: true },
    ],
    assets: {
      vocals: {
        id: "stem-vocals-1",
        songId: "demo-song-1",
        stemType: "vocals",
        blobPath: "https://assets.mixkit.co/music/preview/mixkit-guitar-acoustic-happy-energy-1111.mp3",
        mimeType: "audio/mp3",
        duration: 120,
        model: "bs-roformer-vocals",
      },
      instrumental: {
        id: "stem-inst-1",
        songId: "demo-song-1",
        stemType: "instrumental",
        blobPath: "https://assets.mixkit.co/music/preview/mixkit-guitar-acoustic-happy-energy-1111.mp3",
        mimeType: "audio/mp3",
        duration: 120,
        model: "bs-roformer-instrumental",
      },
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    schemaVersion: "1.0",
    id: "demo-song-2",
    slug: "noches-de-bohemia",
    title: "Noches de Bohemia",
    artist: "Trío Acústico",
    album: "En Vivo",
    language: "es",
    originalAudioUrl: "https://assets.mixkit.co/music/preview/mixkit-acoustic-guitar-chill-1112.mp3",
    audioHash: "f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2",
    music: {
      originalKey: "Am",
      preferredKey: "Am",
      chordShapeKey: "Am",
      capo: 0,
      tuning: "E A D G B E",
      bpm: 84,
      timeSignature: "4/4",
    },
    display: {
      fontScale: 1.0,
      readingMode: "large",
      showChords: true,
      showSections: true,
      autoscrollSpeed: 2,
    },
    tags: ["bolero", "guitarra", "melancólico"],
    isFavorite: false,
    status: "ready",
    lastPracticedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    lyrics: {
      sections: [
        {
          type: "verse",
          label: "Verso 1",
          lines: [
            {
              text: "La luna llena ilumina mi balcón",
              chords: [
                { symbol: "Am", charIndex: 0 },
                { symbol: "Dm", charIndex: 14 },
              ],
              startMs: 0,
              endMs: 6000,
            },
            {
              text: "trayendo recuerdos de un viejo amor",
              chords: [
                { symbol: "G", charIndex: 0 },
                { symbol: "C", charIndex: 18 },
                { symbol: "E7", charIndex: 30 },
              ],
              startMs: 6100,
              endMs: 12000,
            },
          ],
        },
      ],
    },
    melody: [],
    assets: {},
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
];
